export const SET_COLORS = "SET_COLORS";
export const SET_BUZZWORDS = "SET_BUZZWORDS";
export const SET_STARWARSNAMES = "SET_STARWARSNAMES";
export const SET_FORTUNECOOKIES = "SET_FORTUNECOOKIES";
export const SET_EMOJIS = "SET_EMOJIS";
